import { ethers } from 'hardhat';

const BASE_URI = '';

const PUNKZ_BASE = `${BASE_URI}/Punkz/`;
const PUNKZ_FIXED_BASE = `${BASE_URI}/Punkz/Fixed/`;
const PUNKZ_BACKGROUND_BASE = `${BASE_URI}/Items/PunkzBackground/`;
const PUNKZ_CAPS_BASE = `${BASE_URI}/Items/PunkzCaps/`;
const PUNKZ_CATALOG_BASE = `${BASE_URI}/Items/PunkzCatalog/`;
const PUNKZ_CHAIN_BASE = `${BASE_URI}/Items/PunkzChain/`;
const PUNKZ_CIGAR_BASE = `${BASE_URI}/Items/PunkzCigar/`;
const PUNKZ_CLOTHING_BASE = `${BASE_URI}/Items/PunkzClothing/`;
const PUNKZ_EARRING_BASE = `${BASE_URI}/Items/PunkzEarring/`;
const PUNKZ_GLASSES_BASE = `${BASE_URI}/Items/PunkzGlasses/`;
const PUNKZ_MASK_BASE = `${BASE_URI}/Items/PunkzMask/`;
const SURPRISE_PACK_BASE = `${BASE_URI}/Items/SurprisePack/`;

const PUNKZ_COLLECTION_META = `${PUNKZ_BASE}meta/collection.json`;
const PUNKZ_BACKGROUND_COLLECTION_META = `${PUNKZ_BACKGROUND_BASE}meta/collection.json`;
const PUNKZ_CAPS_COLLECTION_META = `${PUNKZ_CAPS_BASE}meta/collection.json`;
const PUNKZ_CATALOG_COLLECTION_META = `${PUNKZ_CATALOG_BASE}meta/collection.json`;
const PUNKZ_CHAIN_COLLECTION_META = `${PUNKZ_CHAIN_BASE}meta/collection.json`;
const PUNKZ_CIGAR_COLLECTION_META = `${PUNKZ_CIGAR_BASE}meta/collection.json`;
const PUNKZ_CLOTHING_COLLECTION_META = `${PUNKZ_CLOTHING_BASE}meta/collection.json`;
const PUNKZ_EARRING_COLLECTION_META = `${PUNKZ_EARRING_BASE}meta/collection.json`;
const PUNKZ_GLASSES_COLLECTION_META = `${PUNKZ_GLASSES_BASE}meta/collection.json`;
const PUNKZ_MASK_COLLECTION_META = `${PUNKZ_MASK_BASE}meta/collection.json`;
const SURPRISE_PACK_COLLECTION_META = `${SURPRISE_PACK_BASE}meta/collection.json`;

const PUNKZ_BASE_META = `${PUNKZ_BASE}meta/`;
const PUNKZ_BACKGROUND_BASE_META = `${PUNKZ_BACKGROUND_BASE}meta/`;
const PUNKZ_CAPS_BASE_META = `${PUNKZ_CAPS_BASE}meta/`;
const PUNKZ_CATALOG_BASE_META = `${PUNKZ_CATALOG_BASE}meta/`;
const PUNKZ_CHAIN_BASE_META = `${PUNKZ_CHAIN_BASE}meta/`;
const PUNKZ_CIGAR_BASE_META = `${PUNKZ_CIGAR_BASE}meta/`;
const PUNKZ_CLOTHING_BASE_META = `${PUNKZ_CLOTHING_BASE}meta/`;
const PUNKZ_EARRING_BASE_META = `${PUNKZ_EARRING_BASE}meta/`;
const PUNKZ_GLASSES_BASE_META = `${PUNKZ_GLASSES_BASE}meta/`;
const PUNKZ_MASK_BASE_META = `${PUNKZ_MASK_BASE}meta/`;
const SURPRISE_PACK_BASE_META = `${SURPRISE_PACK_BASE}meta/`;

const SKIN_BASE_META = `${PUNKZ_FIXED_BASE}/Skin/`;
const MOUTH_BASE_META = `${PUNKZ_FIXED_BASE}/Mouth/`;
const EYES_BASE_META = `${PUNKZ_FIXED_BASE}/Eyes/`;
const EYECOLOR_BASE_META = `${PUNKZ_FIXED_BASE}/Eyecolor/`;
const EYEBROWS_BASE_META = `${PUNKZ_FIXED_BASE}/Eyebrows/`;
const HAIR_BASE_META = `${PUNKZ_FIXED_BASE}/Hair/`;
const NOSE_BASE_META = `${PUNKZ_FIXED_BASE}/Nose/`;
const BEARD_BASE_META = `${PUNKZ_FIXED_BASE}/Beard/`;
const TONGUE_BASE_META = `${PUNKZ_FIXED_BASE}/Tongue/`;

const MAX_SUPPLY = 10000;
const ROYALTY_PERCENTAGE_BPS = 500; // 5%
const PRICE_PER_MINT_COMMON = ethers.utils.parseEther('0.01');
const PRICE_PER_MINT_RARE = ethers.utils.parseEther('0.05');
const PRICE_PER_MINT_EPIC = ethers.utils.parseEther('0.1');
const ITEM_TYPE_SLOT = 1;
const ITEM_TYPE_FIXED = 2;

const BACKGROUND_Z_INDEX = 0;
const SKIN_Z_INDEX = 3;
const BEARD_Z_INDEX = 6;
const MOUTH_Z_INDEX = 7;
const EYECOLOR_Z_INDEX = 8;
const EYES_Z_INDEX = 9;
const EYEBROWS_Z_INDEX = 10;
const NOSE_Z_INDEX = 11;
const SKULLMASK_Z_INDEX = 12;
const TONGUE_Z_INDEX = 13;
const HAIR_Z_INDEX = 14;
const CHAIN_Z_INDEX = 16;
const EARRING_Z_INDEX = 17;
const CLOTHING_Z_INDEX = 18;
const GLASSES_Z_INDEX = 19;
const CAP_Z_INDEX = 20;
const MASK_Z_INDEX = 21;
const CIGAR_Z_INDEX = 22;

export {
  PUNKZ_BASE_META,
  PUNKZ_BACKGROUND_BASE_META,
  PUNKZ_CAPS_BASE_META,
  PUNKZ_CATALOG_BASE_META,
  PUNKZ_CHAIN_BASE_META,
  PUNKZ_CIGAR_BASE_META,
  PUNKZ_CLOTHING_BASE_META,
  PUNKZ_EARRING_BASE_META,
  PUNKZ_GLASSES_BASE_META,
  PUNKZ_MASK_BASE_META,
  SURPRISE_PACK_BASE_META,
  PUNKZ_COLLECTION_META,
  PUNKZ_BACKGROUND_COLLECTION_META,
  PUNKZ_CAPS_COLLECTION_META,
  PUNKZ_CATALOG_COLLECTION_META,
  PUNKZ_CHAIN_COLLECTION_META,
  PUNKZ_CIGAR_COLLECTION_META,
  PUNKZ_CLOTHING_COLLECTION_META,
  PUNKZ_EARRING_COLLECTION_META,
  PUNKZ_GLASSES_COLLECTION_META,
  PUNKZ_MASK_COLLECTION_META,
  SURPRISE_PACK_COLLECTION_META,
  MAX_SUPPLY,
  ROYALTY_PERCENTAGE_BPS,
  PRICE_PER_MINT_COMMON,
  PRICE_PER_MINT_RARE,
  PRICE_PER_MINT_EPIC,
  ITEM_TYPE_SLOT,
  ITEM_TYPE_FIXED,
  SKIN_Z_INDEX,
  MOUTH_Z_INDEX,
  EYES_Z_INDEX,
  EYECOLOR_Z_INDEX,
  EYEBROWS_Z_INDEX,
  HAIR_Z_INDEX,
  NOSE_Z_INDEX,
  BEARD_Z_INDEX,
  TONGUE_Z_INDEX,
  BACKGROUND_Z_INDEX,
  CLOTHING_Z_INDEX,
  CAP_Z_INDEX,
  CHAIN_Z_INDEX,
  CIGAR_Z_INDEX,
  EARRING_Z_INDEX,
  GLASSES_Z_INDEX,
  SKULLMASK_Z_INDEX,
  MASK_Z_INDEX,
  SKIN_BASE_META,
  MOUTH_BASE_META,
  EYES_BASE_META,
  EYECOLOR_BASE_META,
  EYEBROWS_BASE_META,
  HAIR_BASE_META,
  NOSE_BASE_META,
  BEARD_BASE_META,
  TONGUE_BASE_META,
};
